const express=require('express'),{Pool}=require('pg'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),cookieParser=require('cookie-parser'),helmet=require('helmet'),compression=require('compression'),rateLimit=require('express-rate-limit'),multer=require('multer'),crypto=require('crypto'),path=require('path');
const app=express(),PORT=process.env.PORT||3000,prod=process.env.NODE_ENV==='production';
if(process.env.TRUST_PROXY) app.set('trust proxy',1);
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:String(process.env.DATABASE_SSL).toLowerCase()==='true'?{rejectUnauthorized:false}:false});
const SECRET=process.env.JWT_SECRET;if(!SECRET||SECRET.length<32) throw Error('JWT_SECRET must be 32+ chars');
function b64u(s){return Buffer.from(s.replace(/-/g,'+').replace(/_/g,'/')+'==','base64')}
async function verifyPassword(password,hash){
 if(String(hash).startsWith('scrypt:')){
  const parts=String(hash).split(':');
  const n=Number(parts[1]),r=Number(parts[2]),p=Number(parts[3]),salt=b64u(parts[4]),expected=b64u(parts[5]);
  const out=await new Promise((resolve,reject)=>crypto.scrypt(String(password),salt,32,{N:n,r,p,maxmem:64*1024*1024},(e,k)=>e?reject(e):resolve(k)));
  return out.length===expected.length&&crypto.timingSafeEqual(out,expected);
 }
 return bcrypt.compare(String(password),hash);
}
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],fontSrc:["'self'",'https://fonts.gstatic.com'],imgSrc:["'self'",'data:','https:'],scriptSrc:["'self'"],connectSrc:["'self'"]}}}));app.use(compression());app.use(cookieParser());app.use(express.json({limit:'300kb'}));
const orderLimit=rateLimit({windowMs:600000,limit:40}),loginLimit=rateLimit({windowMs:900000,limit:12});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:4*1024*1024},fileFilter:(_req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(file.mimetype))});
const sseClients=new Set();
function broadcast(event,payload){const body='event: '+event+'\ndata: '+JSON.stringify(payload)+'\n\n';for(const res of sseClients){try{res.write(body)}catch{sseClients.delete(res)}}}
const statusTransitions={PENDING:['CONFIRMED','REJECTED','CANCELLED'],CONFIRMED:['PREPARING','CANCELLED'],PREPARING:['READY','CANCELLED'],READY:['COMPLETED','CANCELLED'],COMPLETED:[],REJECTED:[],CANCELLED:[]};
const safe=(v,n=500)=>String(v??'').trim().slice(0,n);
const money=v=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.round(n*100)/100):0};
const cats=[['shellfish','القشريات والطواجن','Seafood & Casseroles','🦐'],['meals','الوجبات والولائم','Meals & Platters','🍽️'],['rice','الأرز والمكرونة','Rice & Pasta','🍚'],['starters','المقبلات والشوربة','Starters & Soup','🥣'],['drinks','المشروبات والحلى','Drinks & Desserts','🥤']];
const products=[
['p001','shellfish','روبيان جامبو (مقلي - مشوي)','Jumbo Shrimp (Fried / Grilled)',100,'حسب الوزن','by weight',1],['p002','shellfish','روبيان وسط (مقلي - مشوي)','Medium Shrimp (Fried / Grilled)',80,'حسب الوزن','by weight',1],['p003','shellfish','كابوريا إناث مشوي','Grilled Female Crab',65,'حسب الوزن','by weight',0],['p004','shellfish','حبار (مقلي - مشوي)','Squid (Fried / Grilled)',80,'حسب الوزن','by weight',0],['p005','shellfish','بلح بحر (شوربة - مقلي - مشوي)','Mussels (Soup / Fried / Grilled)',100,'حسب الوزن','by weight',0],['p006','shellfish','استاكوزا مشوي','Grilled Lobster',120,'حسب الوزن','by weight',1],['p007','shellfish','طاجن سي فود (صوص بالكريمة)','Seafood Casserole - Cream Sauce',40,'طبق','dish',1],['p008','shellfish','طاجن روبيان (صوص طماطم)','Shrimp Casserole - Tomato Sauce',35,'طبق','dish',0],['p009','shellfish','طاجن حبار (صوص كريمة)','Squid Casserole - Cream Sauce',40,'طبق','dish',0],['p010','shellfish','طاجن فيليه (صوص طماطم)','Fish Fillet Casserole - Tomato Sauce',35,'طبق','dish',0],['p050','shellfish','كيس شريمب','Shrimp Bag',60,'طبق','dish',1],
['p011','meals','وجبة فيليه (مشوي - مقلي) مع الأرز والسلطات','Fish Fillet Meal with Rice & Salads',25,'وجبة','meal',0],['p012','meals','وجبة بلطي (مشوي - مقلي) مع الأرز والسلطات','Tilapia Meal with Rice & Salads',25,'وجبة','meal',0],['p013','meals','وجبة سالمون (مشوي - مقلي) مع الأرز والسلطات','Salmon Meal with Rice & Salads',45,'وجبة','meal',1],['p014','meals','وجبة دنيس (مشوي بالزيت والليمون) مع الأرز والسلطات','Sea Bream with Oil & Lemon, Rice & Salads',40,'وجبة','meal',0],['p015','meals','وجبة هامور مسكوفه بالفرن','Oven-Baked Hammour Meal',45,'وجبة','meal',0],['p016','meals','وجبة كنعد (مشوي - مقلي) مع الأرز والسلطات','Kingfish Meal with Rice & Salads',45,'وجبة','meal',0],['p017','meals','وجبة روبيان','Shrimp Meal',35,'وجبة','meal',1],['p018','meals','صحن زعانف الروبيان 12-14 فرد','Shrimp Fins Platter - 12 to 14 People',600,'صحن','platter',1],['p019','meals','صحن الشيف 8-12 فرد','Chef Platter - 8 to 12 People',500,'صحن','platter',1],['p020','meals','صحن وسط 6-8 أفراد','Medium Platter - 6 to 8 People',300,'صحن','platter',0],
['p021','rice','أرز صيادية','Sayadiya Rice',8,'طبق','dish',0],['p022','rice','أرز أبيض','White Rice',7,'طبق','dish',0],['p023','rice','أرز بالروبيان','Shrimp Rice',25,'طبق','dish',1],['p024','rice','أرز زعانف الروبيان','Shrimp Fins Rice',30,'طبق','dish',0],['p025','rice','اسباجيتي سي فود صوص كريمة','Seafood Spaghetti - Cream Sauce',30,'طبق','dish',0],['p026','rice','اسباجيتي روبيان صوص أحمر','Shrimp Spaghetti - Red Sauce',30,'طبق','dish',0],['p027','rice','اسباجيتي روبيان وايت صوص','Shrimp Spaghetti - White Sauce',35,'طبق','dish',0],['p028','rice','فوتوتشيني سي فود بالكريم','Creamy Seafood Fettuccine',35,'طبق','dish',1],
['p029','starters','سلطة طحينة','Tahini Salad',5,'طبق','dish',0],['p030','starters','سلطة طماطم متبلة','Seasoned Tomato Salad',5,'طبق','dish',0],['p031','starters','سلطة خضار','Green Salad',5,'طبق','dish',0],['p032','starters','سلطة حارة','Spicy Salad',5,'طبق','dish',0],['p051','starters','سلطة رنجة','Herring Salad',12,'طبق','dish',0],['p033','starters','باذنجان مخلل','Pickled Eggplant',5,'طبق','dish',0],['p034','starters','خبز','Bread',1,'حبة','piece',0],['p035','starters','شوربة زعانف الروبيان','Shrimp Fins Soup',35,'طبق','dish',1],['p036','starters','شوربة سي فود بالعظم','Bone-in Seafood Soup',25,'طبق','dish',0],['p037','starters','شوربة سي فود مخلي','Boneless Seafood Soup',25,'طبق','dish',0],['p038','starters','شوربة روبيان','Shrimp Soup',25,'طبق','dish',0],['p052','starters','ملوخية بالروبيان','Molokhia with Shrimp',25,'طبق','dish',0],
['p039','drinks','بيبسي','Pepsi',3,'علبة','can',0],['p040','drinks','سفن أب','7UP',3,'علبة','can',0],['p041','drinks','حمضيات','Citrus Drink',3,'علبة','can',0],['p042','drinks','كنزا','Kinza',2.5,'علبة','can',0],['p053','drinks','استريم','Stream Drink',2.5,'علبة','can',0],['p043','drinks','مياه','Water',1,'عبوة','bottle',0],['p044','drinks','عصير برتقال','Orange Juice',10,'كوب','cup',0],['p045','drinks','عصير مانجو','Mango Juice',12,'كوب','cup',0],['p046','drinks','عصير فراولة','Strawberry Juice',10,'كوب','cup',0],['p047','drinks','عصير ليمون','Lemon Juice',10,'كوب','cup',0],['p048','drinks','أرز بلبن','Rice Pudding',10,'طبق','dish',0],['p049','drinks','كريم كراميل','Crème Caramel',7,'طبق','dish',0]];
const offers=[['o001','صحن التوفير من 3 إلى 4 فرد','Saving Platter - 3 to 4 People',150],['o002','صينية الكيف الحلو','Al Kaif Seafood Tray',120],['o003','صينية العريس','Al Arees Seafood Tray',250],['o008','صينية الدنيس بالبطاطس','Sea Bream & Potato Tray',120],['o004','صحن زعانف الروبيان 12-14 فرد','Grand Platter - 12 to 14 People',600],['o005','صحن الشيف من 8 إلى 12 فرد','Chef Platter - 8 to 12 People',500],['o006','صحن وسط من 6 إلى 8 أفراد','Medium Platter - 6 to 8 People',300],['o007','صحن المزاجنجية من 5 إلى 6 فرد','Mood Platter - 5 to 6 People',200]];
const px=(id,w=900,h=650)=>'https://images.pexels.com/photos/'+id+'/pexels-photo-'+id+'.jpeg?auto=compress&cs=tinysrgb&w='+w+'&h='+h+'&fit=crop';
const productImages={p001:px(39035466),p002:px(36720618),p003:px(4869328),p004:px(4869328),p005:px(9328460),p006:px(566343),p007:px(6262224),p008:px(17600198),p009:px(4869328),p010:px(6046671),p050:px(39035466),p011:px(6046671),p012:px(19106459),p013:px(31235406),p014:px(25004921),p015:px(17010947),p016:px(32668760),p017:px(30749023),p018:px(8352805),p019:px(566343),p020:px(32668760),p021:px(15362105),p022:px(8423376),p023:px(37215009),p024:px(8352805),p025:px(33323283),p026:px(33323283),p027:px(33323283),p028:px(33323283),p029:px(4989069),p030:px(4989069),p031:px(4989069),p032:px(4989069),p051:px(4989069),p033:px(10563268),p034:px(6419753),p035:px(18510254),p036:px(23627792),p037:px(23627792),p038:px(14856117),p052:px(6262224),p039:px(4113632),p040:px(8880742),p041:px(4871113),p042:px(8880742),p053:px(8880742),p043:px(15624409),p044:px(12222086),p045:px(7656388),p046:px(4871113),p047:px(8215113),p048:px(116725),p049:px(34468155)};
const offerImages={o001:px(37215009,1100,700),o002:px(32668760,1100,700),o003:px(566343,1100,700),o008:px(25004921,1100,700),o004:px(8352805,1100,700),o005:px(566345,1100,700),o006:px(30749023,1100,700),o007:px(4869328,1100,700)};
const categoryDescriptions={shellfish:['مأكولات بحرية طازجة ومحضرة حسب الطلب.','Fresh seafood prepared to order.'],meals:['وجبة بحرية متكاملة محضرة طازجاً.','A complete seafood meal prepared fresh.'],rice:['طبق أرز أو مكرونة محضر طازجاً بنكهات زعانف.','Fresh rice or pasta prepared in the Shrimp Fins style.'],starters:['مقبلات أو شوربة طازجة لتكمل وجبتك.','Fresh starter or soup to complete your meal.'],drinks:['مشروب أو حلى يقدم طازجاً.','A refreshing drink or dessert.']};

async function init(){await pool.query(`
CREATE TABLE IF NOT EXISTS settings(id int primary key,data jsonb not null);
CREATE TABLE IF NOT EXISTS categories(id text primary key,name_ar text,name_en text,icon text,active boolean default true,sort_order int default 0);
CREATE TABLE IF NOT EXISTS products(id text primary key,category_id text references categories(id),name_ar text,name_en text,price numeric(10,2),unit_ar text,unit_en text,available boolean default true,featured boolean default false,sort_order int default 0);
CREATE TABLE IF NOT EXISTS offers(id text primary key,title_ar text,title_en text,price numeric(10,2),active boolean default true,sort_order int default 0);
CREATE TABLE IF NOT EXISTS admins(id bigserial primary key,email text unique,name text,password_hash text,active boolean default true);
CREATE TABLE IF NOT EXISTS orders(id text primary key,order_no text unique,token text unique,customer_name text,phone text,order_type text,address text,notes text,payment text,subtotal numeric(10,2),delivery_fee numeric(10,2),total numeric(10,2),status text,status_note text,estimated_minutes int,created_at timestamptz default now(),updated_at timestamptz default now());
CREATE TABLE IF NOT EXISTS order_items(id bigserial primary key,order_id text references orders(id) on delete cascade,product_id text,name_ar text,name_en text,price numeric(10,2),qty int,total numeric(10,2));
CREATE TABLE IF NOT EXISTS order_history(id bigserial primary key,order_id text references orders(id) on delete cascade,status text,note text,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS images(id text primary key,mime_type text not null,data bytea not null,created_at timestamptz default now());
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_ar text NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_en text NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS image text NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS compare_at_price numeric(10,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE offers ADD COLUMN IF NOT EXISTS description_ar text NOT NULL DEFAULT '';
ALTER TABLE offers ADD COLUMN IF NOT EXISTS description_en text NOT NULL DEFAULT '';
ALTER TABLE offers ADD COLUMN IF NOT EXISTS image text NOT NULL DEFAULT '';
ALTER TABLE offers ADD COLUMN IF NOT EXISTS starts_at timestamptz;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS ends_at timestamptz;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE offers ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE admins ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'ADMIN';
ALTER TABLE admins ADD COLUMN IF NOT EXISTS last_login_at timestamptz;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE admins ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();`);
let c=+(await pool.query('select count(*) c from settings')).rows[0].c;if(!c)await pool.query('insert into settings values(1,$1)',[{restaurantNameAr:'زعانف الروبيان',restaurantNameEn:'Shrimp Fins',phone:'0541064143',whatsapp:'966541064143',addressAr:'الرياض - حي النسيم الغربي - شارع حسان بن ثابت، بجوار تقاطع أحمد بن حنبل',addressEn:'Riyadh - Al Naseem Al Gharbi, Hassan Bin Thabit St',deliveryFee:10,minimumOrder:30,acceptingOrders:true,currency:'SAR'}]);
c=+(await pool.query('select count(*) c from categories')).rows[0].c;if(!c)for(let i=0;i<cats.length;i++)await pool.query('insert into categories values($1,$2,$3,$4,true,$5)',[...cats[i],i]);
c=+(await pool.query('select count(*) c from products')).rows[0].c;if(!c)for(let i=0;i<products.length;i++){let p=products[i];await pool.query('insert into products(id,category_id,name_ar,name_en,price,unit_ar,unit_en,available,featured,sort_order) values($1,$2,$3,$4,$5,$6,$7,true,$8,$9)',[...p.slice(0,7),!!p[7],i]);}
c=+(await pool.query('select count(*) c from offers')).rows[0].c;if(!c)for(let i=0;i<offers.length;i++)await pool.query('insert into offers values($1,$2,$3,$4,true,$5)',[...offers[i],i]);
c=+(await pool.query('select count(*) c from admins')).rows[0].c;if(!c){let e=process.env.ADMIN_EMAIL,h=process.env.ADMIN_PASSWORD_HASH;if(!e||!h)throw Error('ADMIN_EMAIL and ADMIN_PASSWORD_HASH required');await pool.query('insert into admins(email,name,password_hash) values($1,$2,$3)',[e.toLowerCase(),process.env.ADMIN_NAME||'Restaurant Admin',h]);}
for(const p of products){const d=categoryDescriptions[p[1]]||['محضر طازجاً حسب الطلب.','Freshly prepared to order.'];await pool.query("update products set image=case when coalesce(image,'')='' then $1 else image end,description_ar=case when coalesce(description_ar,'')='' then $2 else description_ar end,description_en=case when coalesce(description_en,'')='' then $3 else description_en end where id=$4",[productImages[p[0]]||'',d[0],d[1],p[0]])}
for(const o of offers){await pool.query("update offers set image=case when coalesce(image,'')='' then $1 else image end,description_ar=case when coalesce(description_ar,'')='' then 'عرض خاص من زعانف الروبيان للمشاركة والعزائم.' else description_ar end,description_en=case when coalesce(description_en,'')='' then 'A special Shrimp Fins offer for sharing and gatherings.' else description_en end where id=$2",[offerImages[o[0]]||'',o[0]])}
let st=(await pool.query('select data from settings where id=1')).rows[0]?.data||{};
if(st.menuRevision!=='menu-2026-09-v2'){
  const client=await pool.connect();
  try{
    await client.query('BEGIN');
    for(let i=0;i<products.length;i++){
      const p=products[i],d=categoryDescriptions[p[1]]||['محضر طازجاً حسب الطلب.','Freshly prepared to order.'];
      await client.query(`INSERT INTO products(id,category_id,name_ar,name_en,description_ar,description_en,price,unit_ar,unit_en,image,available,featured,sort_order)
        VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,TRUE,$11,$12)
        ON CONFLICT(id) DO UPDATE SET category_id=EXCLUDED.category_id,name_ar=EXCLUDED.name_ar,name_en=EXCLUDED.name_en,price=EXCLUDED.price,unit_ar=EXCLUDED.unit_ar,unit_en=EXCLUDED.unit_en,sort_order=EXCLUDED.sort_order,
        image=CASE WHEN COALESCE(products.image,'')='' THEN EXCLUDED.image ELSE products.image END,
        description_ar=CASE WHEN COALESCE(products.description_ar,'')='' THEN EXCLUDED.description_ar ELSE products.description_ar END,
        description_en=CASE WHEN COALESCE(products.description_en,'')='' THEN EXCLUDED.description_en ELSE products.description_en END,updated_at=NOW()`,
        [p[0],p[1],p[2],p[3],d[0],d[1],p[4],p[5],p[6],productImages[p[0]]||'',!!p[7],i]);
    }
    for(let i=0;i<offers.length;i++){
      const o=offers[i];
      await client.query(`INSERT INTO offers(id,title_ar,title_en,description_ar,description_en,price,image,active,sort_order)
        VALUES($1,$2,$3,$4,$5,$6,$7,TRUE,$8)
        ON CONFLICT(id) DO UPDATE SET title_ar=EXCLUDED.title_ar,title_en=EXCLUDED.title_en,price=EXCLUDED.price,sort_order=EXCLUDED.sort_order,
        image=CASE WHEN COALESCE(offers.image,'')='' THEN EXCLUDED.image ELSE offers.image END,
        description_ar=CASE WHEN COALESCE(offers.description_ar,'')='' THEN EXCLUDED.description_ar ELSE offers.description_ar END,
        description_en=CASE WHEN COALESCE(offers.description_en,'')='' THEN EXCLUDED.description_en ELSE offers.description_en END,updated_at=NOW()`,
        [o[0],o[1],o[2],'عرض خاص من زعانف الروبيان للمشاركة والعزائم.','A special Shrimp Fins offer for sharing and gatherings.',o[3],offerImages[o[0]]||'',i]);
    }
    st.menuRevision='menu-2026-09-v2';st.menuSource='Restaurant menu artwork supplied by owner';st.menuProductCount=products.length;st.menuOfferCount=offers.length;
    await client.query('UPDATE settings SET data=$1 WHERE id=1',[st]);
    await client.query('COMMIT');
  }catch(e){await client.query('ROLLBACK').catch(()=>{});throw e}finally{client.release()}
}
st={restaurantNameAr:'زعانف الروبيان',restaurantNameEn:'Shrimp Fins',phone:'0541064143',whatsapp:'966541064143',addressAr:'الرياض - حي النسيم الغربي - شارع حسان بن ثابت، بجوار تقاطع أحمد بن حنبل',addressEn:'Riyadh - Al Naseem Al Gharbi, Hassan Bin Thabit St',deliveryFee:10,minimumOrder:30,acceptingOrders:true,currency:'SAR',heroMessageAr:'أشهى المأكولات البحرية الطازجة في مكان واحد',heroMessageEn:'Premium fresh seafood, prepared to order',openingHoursAr:'يومياً — تواصل معنا لتأكيد ساعات العمل',openingHoursEn:'Daily — contact us to confirm opening hours',mapQuery:'زعانف الروبيان، حي النسيم الغربي، الرياض',heroImage:px(8352805,1600,950),imageCredit:'Licensed Pexels stock photography is used where real restaurant dish photos are not yet available.',...st};await pool.query('update settings set data=$1 where id=1',[st]);}
const auth=(req,res,next)=>{try{req.admin=jwt.verify(req.cookies.sf_admin,SECRET);next()}catch{return res.status(401).json({error:'Unauthorized'})}};
app.get('/api/health',async(req,res)=>{try{await pool.query('select 1');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.get('/api/images/:id',async(req,res,next)=>{try{const r=await pool.query('select mime_type,data from images where id=$1',[safe(req.params.id,100)]);if(!r.rows[0])return res.status(404).end();res.set('Content-Type',r.rows[0].mime_type).set('Cache-Control','public,max-age=31536000,immutable').send(r.rows[0].data)}catch(e){next(e)}});
app.get('/api/public',async(req,res)=>{const[s,c,p,o]=await Promise.all([pool.query('select data from settings where id=1'),pool.query('select * from categories where active=true order by sort_order'),pool.query('select * from products where available=true order by featured desc,sort_order'),pool.query('select * from offers where active=true order by sort_order')]);res.json({settings:s.rows[0].data,categories:c.rows,products:p.rows.map(x=>({...x,price:+x.price})),offers:o.rows.map(x=>({...x,price:+x.price}))})});
app.post('/api/orders',orderLimit,async(req,res)=>{const b=req.body||{},name=String(b.customerName||'').trim().slice(0,80),phone=String(b.phone||'').replace(/\D/g,'').slice(0,20),type=b.orderType==='delivery'?'delivery':'pickup',address=String(b.address||'').trim().slice(0,300);if(name.length<2||phone.length<9||!Array.isArray(b.items)||!b.items.length)return res.status(400).json({error:'Please complete your order details.'});if(type==='delivery'&&address.length<5)return res.status(400).json({error:'Delivery address is required.'});const ids=b.items.map(x=>String(x.productId));const pr=(await pool.query('select * from products where id=any($1::text[]) and available=true',[ids])).rows;let items=[];for(const raw of b.items){let p=pr.find(x=>x.id===String(raw.productId));if(!p)return res.status(409).json({error:'A selected item is unavailable.'});let q=Math.max(1,Math.min(50,Math.floor(+raw.qty||1)));items.push({p,q,total:+p.price*q})}let subtotal=items.reduce((a,x)=>a+x.total,0),st=(await pool.query('select data from settings where id=1')).rows[0].data;if(st.acceptingOrders===false)return res.status(409).json({error:'Restaurant is currently not accepting orders.'});if(subtotal<+(st.minimumOrder||0))return res.status(400).json({error:'Minimum order is '+st.minimumOrder+' SAR.'});let fee=type==='delivery'?+(st.deliveryFee||0):0,total=subtotal+fee,id='ord_'+crypto.randomUUID(),token=crypto.randomBytes(24).toString('base64url'),no='SF'+Date.now().toString(36).toUpperCase()+crypto.randomBytes(2).toString('hex').toUpperCase();const client=await pool.connect();try{await client.query('BEGIN');await client.query(`insert into orders(id,order_no,token,customer_name,phone,order_type,address,notes,payment,subtotal,delivery_fee,total,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'PENDING')`,[id,no,token,name,phone,type,address,String(b.notes||'').slice(0,500),String(b.paymentMethod||'cash').slice(0,30),subtotal,fee,total]);for(const x of items)await client.query('insert into order_items(order_id,product_id,name_ar,name_en,price,qty,total) values($1,$2,$3,$4,$5,$6,$7)',[id,x.p.id,x.p.name_ar,x.p.name_en,x.p.price,x.q,x.total]);await client.query("insert into order_history(order_id,status,note) values($1,'PENDING','Order submitted by customer')",[id]);await client.query('COMMIT');broadcast('new-order',{orderNumber:no,total,status:'PENDING',customerName:name,createdAt:new Date().toISOString()});res.status(201).json({ok:true,order:{orderNumber:no,trackingToken:token,status:'PENDING',total}})}catch(e){await client.query('ROLLBACK').catch(()=>{});throw e}finally{client.release()}});
app.get('/api/orders/track/:token',orderLimit,async(req,res)=>{let phone=String(req.query.phone||'').replace(/\D/g,'');let o=(await pool.query('select * from orders where token=$1 and right(phone,8)=right($2,8)',[req.params.token,phone])).rows[0];if(!o)return res.status(404).json({error:'Order not found.'});let [it,h]=await Promise.all([pool.query('select * from order_items where order_id=$1',[o.id]),pool.query('select status,note,created_at from order_history where order_id=$1 order by id',[o.id])]);res.json({order:{orderNumber:o.order_no,status:o.status,statusNote:o.status_note,estimatedMinutes:o.estimated_minutes,total:+o.total,createdAt:o.created_at,items:it.rows,history:h.rows}})});
app.post('/api/admin/login',loginLimit,async(req,res)=>{let email=String(req.body.email||'').toLowerCase(),a=(await pool.query('select * from admins where email=$1 and active=true',[email])).rows[0];if(!a||!await verifyPassword(String(req.body.password||''),a.password_hash))return res.status(401).json({error:'Invalid login'});let t=jwt.sign({sub:String(a.id),email:a.email,name:a.name},SECRET,{expiresIn:'12h'});res.cookie('sf_admin',t,{httpOnly:true,secure:prod,sameSite:'strict',maxAge:43200000});res.json({ok:true,admin:{name:a.name,email:a.email}})});
app.post('/api/admin/logout',auth,(req,res)=>{res.clearCookie('sf_admin');res.json({ok:true})});app.get('/api/admin/me',auth,(req,res)=>res.json({admin:req.admin}));
app.use('/api/admin',auth);
app.get('/api/admin/events',(req,res)=>{res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.flushHeaders?.();sseClients.add(res);res.write('event: ready\ndata: {}\n\n');req.on('close',()=>sseClients.delete(res))});
app.get('/api/admin/dashboard',async(req,res)=>{let [today,pending,pc,oc,recent,month,top]=await Promise.all([pool.query("select count(*) c,coalesce(sum(case when status='COMPLETED' then total else 0 end),0) sales from orders where created_at::date=current_date"),pool.query("select count(*) c from orders where status='PENDING'"),pool.query('select count(*) c from products'),pool.query("select count(*) c from offers where active=true"),pool.query('select * from orders order by created_at desc limit 12'),pool.query("select coalesce(sum(total),0) sales from orders where status='COMPLETED' and date_trunc('month',created_at)=date_trunc('month',current_date)"),pool.query("select name_en,name_ar,sum(qty)::int qty,sum(total)::numeric(12,2) revenue from order_items group by name_en,name_ar order by qty desc limit 8")]);res.json({todayOrders:+today.rows[0].c,todaySales:+today.rows[0].sales,pending:+pending.rows[0].c,products:+pc.rows[0].c,offers:+oc.rows[0].c,monthSales:+month.rows[0].sales,recent:recent.rows,topItems:top.rows})});
app.get('/api/admin/orders',async(req,res)=>{let args=[],where=[];if(req.query.status){args.push(String(req.query.status));where.push('status=$'+args.length)}if(req.query.q){args.push('%'+String(req.query.q).slice(0,100)+'%');where.push('(order_no ilike $'+args.length+' or customer_name ilike $'+args.length+' or phone ilike $'+args.length+')')}let r=await pool.query('select * from orders '+(where.length?'where '+where.join(' and '):'')+' order by created_at desc limit 500',args);res.json({orders:r.rows})});
app.get('/api/admin/orders/:id',async(req,res)=>{let o=(await pool.query('select * from orders where id=$1',[req.params.id])).rows[0];if(!o)return res.status(404).json({error:'Order not found'});let [items,h]=await Promise.all([pool.query('select * from order_items where order_id=$1 order by id',[o.id]),pool.query('select * from order_history where order_id=$1 order by id',[o.id])]);res.json({order:o,items:items.rows,history:h.rows})});
app.patch('/api/admin/orders/:id/status',async(req,res,nextFn)=>{const client=await pool.connect();try{await client.query('BEGIN');let current=(await client.query('select * from orders where id=$1 for update',[req.params.id])).rows[0];if(!current){await client.query('ROLLBACK');return res.status(404).json({error:'Order not found'})}let next=String(req.body.status||'');if(!(statusTransitions[current.status]||[]).includes(next)){await client.query('ROLLBACK');return res.status(409).json({error:'Invalid transition from '+current.status+' to '+next})}let note=safe(req.body.note,300),mins=req.body.estimatedMinutes==null?null:Math.max(1,Math.min(240,+req.body.estimatedMinutes||1));let r=await client.query("update orders set status=$1,status_note=case when $2='' then status_note else $2 end,estimated_minutes=coalesce($3,estimated_minutes),updated_at=now() where id=$4 returning *",[next,note,mins,req.params.id]);await client.query('insert into order_history(order_id,status,note) values($1,$2,$3)',[req.params.id,next,note]);await client.query('COMMIT');broadcast('order-status',{id:req.params.id,status:next});res.json({order:r.rows[0]})}catch(e){await client.query('ROLLBACK').catch(()=>{});nextFn(e)}finally{client.release()}});
app.get('/api/admin/categories',async(req,res)=>res.json({categories:(await pool.query('select * from categories order by sort_order,name_ar')).rows}));
app.post('/api/admin/categories',async(req,res)=>{let b=req.body||{},id=safe(b.id||('cat_'+crypto.randomUUID()),80).toLowerCase().replace(/[^a-z0-9_-]/g,'-');try{let r=await pool.query('insert into categories(id,name_ar,name_en,icon,active,sort_order) values($1,$2,$3,$4,$5,$6) returning *',[id,safe(b.name_ar,100),safe(b.name_en,100),safe(b.icon||'🍽️',10),b.active!==false,+b.sort_order||999]);res.status(201).json({category:r.rows[0]})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Category already exists'});throw e}});
app.patch('/api/admin/categories/:id',async(req,res)=>{let b=req.body||{};let r=await pool.query('update categories set name_ar=coalesce($1,name_ar),name_en=coalesce($2,name_en),icon=coalesce($3,icon),active=coalesce($4,active),sort_order=coalesce($5,sort_order),updated_at=now() where id=$6 returning *',[b.name_ar??null,b.name_en??null,b.icon??null,b.active==null?null:!!b.active,b.sort_order==null?null:+b.sort_order,req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Category not found'});res.json({category:r.rows[0]})});app.delete('/api/admin/categories/:id',async(req,res)=>{let used=+(await pool.query('select count(*) c from products where category_id=$1',[req.params.id])).rows[0].c;if(used)return res.status(409).json({error:'Category is used by '+used+' product(s). Move or delete those products first.'});let r=await pool.query('delete from categories where id=$1 returning id',[req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Category not found'});res.json({ok:true})});
app.get('/api/admin/products',async(req,res)=>res.json({products:(await pool.query('select p.*,c.name_ar category_ar,c.name_en category_en from products p join categories c on c.id=p.category_id order by c.sort_order,p.sort_order,p.name_ar')).rows,categories:(await pool.query('select * from categories order by sort_order')).rows}));
app.post('/api/admin/products',async(req,res)=>{let b=req.body||{},id='prd_'+crypto.randomUUID();try{let r=await pool.query('insert into products(id,category_id,name_ar,name_en,description_ar,description_en,price,compare_at_price,unit_ar,unit_en,image,available,featured,sort_order) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *',[id,safe(b.category_id||b.categoryId,80),safe(b.name_ar,150),safe(b.name_en,150),safe(b.description_ar,700),safe(b.description_en,700),money(b.price),b.compare_at_price==null?null:money(b.compare_at_price),safe(b.unit_ar||'طبق',60),safe(b.unit_en||'item',60),safe(b.image,500),b.available!==false,!!b.featured,+b.sort_order||999]);res.status(201).json({product:r.rows[0]})}catch(e){if(e.code==='23503')return res.status(400).json({error:'Invalid category'});throw e}});
app.patch('/api/admin/products/:id',async(req,res)=>{let b=req.body||{},p=(await pool.query('select * from products where id=$1',[req.params.id])).rows[0];if(!p)return res.status(404).json({error:'Product not found'});let r=await pool.query('update products set category_id=$1,name_ar=$2,name_en=$3,description_ar=$4,description_en=$5,price=$6,compare_at_price=$7,unit_ar=$8,unit_en=$9,image=$10,available=$11,featured=$12,sort_order=$13,updated_at=now() where id=$14 returning *',[safe(b.category_id??b.categoryId??p.category_id,80),safe(b.name_ar??p.name_ar,150),safe(b.name_en??p.name_en,150),safe(b.description_ar??p.description_ar,700),safe(b.description_en??p.description_en,700),b.price==null?+p.price:money(b.price),b.compare_at_price===undefined?p.compare_at_price:(b.compare_at_price==null?null:money(b.compare_at_price)),safe(b.unit_ar??p.unit_ar,60),safe(b.unit_en??p.unit_en,60),safe(b.image??p.image,500),b.available==null?p.available:!!b.available,b.featured==null?p.featured:!!b.featured,b.sort_order==null?p.sort_order:+b.sort_order,req.params.id]);res.json({product:r.rows[0]})});
app.delete('/api/admin/products/:id',async(req,res)=>{let r=await pool.query('delete from products where id=$1 returning id',[req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Product not found'});res.json({ok:true})});
app.get('/api/admin/offers',async(req,res)=>res.json({offers:(await pool.query('select * from offers order by sort_order,title_ar')).rows}));
app.post('/api/admin/offers',async(req,res)=>{let b=req.body||{},id='off_'+crypto.randomUUID();let r=await pool.query('insert into offers(id,title_ar,title_en,description_ar,description_en,price,image,active,sort_order,starts_at,ends_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *',[id,safe(b.title_ar,160),safe(b.title_en,160),safe(b.description_ar,800),safe(b.description_en,800),money(b.price),safe(b.image,500),b.active!==false,+b.sort_order||999,b.starts_at||null,b.ends_at||null]);res.status(201).json({offer:r.rows[0]})});
app.patch('/api/admin/offers/:id',async(req,res)=>{let b=req.body||{},o=(await pool.query('select * from offers where id=$1',[req.params.id])).rows[0];if(!o)return res.status(404).json({error:'Offer not found'});let r=await pool.query('update offers set title_ar=$1,title_en=$2,description_ar=$3,description_en=$4,price=$5,image=$6,active=$7,sort_order=$8,starts_at=$9,ends_at=$10,updated_at=now() where id=$11 returning *',[safe(b.title_ar??o.title_ar,160),safe(b.title_en??o.title_en,160),safe(b.description_ar??o.description_ar,800),safe(b.description_en??o.description_en,800),b.price==null?+o.price:money(b.price),safe(b.image??o.image,500),b.active==null?o.active:!!b.active,b.sort_order==null?o.sort_order:+b.sort_order,b.starts_at===undefined?o.starts_at:(b.starts_at||null),b.ends_at===undefined?o.ends_at:(b.ends_at||null),req.params.id]);res.json({offer:r.rows[0]})});
app.delete('/api/admin/offers/:id',async(req,res)=>{let r=await pool.query('delete from offers where id=$1 returning id',[req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Offer not found'});res.json({ok:true})});
app.post('/api/admin/images',upload.single('image'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'JPEG, PNG or WebP image required'});let id='img_'+crypto.randomUUID();await pool.query('insert into images(id,mime_type,data) values($1,$2,$3)',[id,req.file.mimetype,req.file.buffer]);res.status(201).json({id,url:'/api/images/'+id})});
app.get('/api/admin/settings',async(req,res)=>res.json({settings:(await pool.query('select data from settings where id=1')).rows[0].data}));
app.put('/api/admin/settings',async(req,res)=>{let old=(await pool.query('select data from settings where id=1')).rows[0].data,b=req.body||{},n={...old};for(const k of ['restaurantNameAr','restaurantNameEn','phone','whatsapp','addressAr','addressEn','heroMessageAr','heroMessageEn','openingHoursAr','openingHoursEn','mapQuery','currency','heroImage','storefrontImage'])if(k in b)n[k]=safe(b[k],k.endsWith('Image')?30000:500);for(const k of ['deliveryFee','minimumOrder'])if(k in b)n[k]=money(b[k]);if('acceptingOrders'in b)n.acceptingOrders=!!b.acceptingOrders;await pool.query('update settings set data=$1 where id=1',[n]);broadcast('settings',{acceptingOrders:n.acceptingOrders});res.json({settings:n})});
app.post('/api/admin/change-password',async(req,res)=>{let a=(await pool.query('select * from admins where id=$1',[req.admin.sub])).rows[0],cur=String(req.body.currentPassword||''),next=String(req.body.newPassword||'');if(next.length<10)return res.status(400).json({error:'New password must be at least 10 characters'});if(!a||!await verifyPassword(cur,a.password_hash))return res.status(401).json({error:'Current password is incorrect'});let hash=await bcrypt.hash(next,12);await pool.query('update admins set password_hash=$1,updated_at=now() where id=$2',[hash,a.id]);res.clearCookie('sf_admin');res.json({ok:true,relogin:true})});
app.get('/api/admin/export',async(req,res)=>{let [settings,categories,products,offers,orders,items,history]=await Promise.all([pool.query('select data from settings where id=1'),pool.query('select * from categories order by sort_order'),pool.query('select * from products order by sort_order'),pool.query('select * from offers order by sort_order'),pool.query('select * from orders order by created_at desc'),pool.query('select * from order_items order by id'),pool.query('select * from order_history order by id')]);res.set('Content-Disposition','attachment; filename="shrimp-fins-backup-'+new Date().toISOString().slice(0,10)+'.json"').json({exportedAt:new Date().toISOString(),settings:settings.rows[0].data,categories:categories.rows,products:products.rows,offers:offers.rows,orders:orders.rows,orderItems:items.rows,orderHistory:history.rows})});
app.use(express.static(path.join(__dirname,'public'),{maxAge:'1h'}));app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((e,req,res,next)=>{console.error(e);res.status(500).json({error:prod?'Unexpected server error':e.message})});
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Shrimp Fins live on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
